[project]
name = "modular-kf"
version = "0.1.0"
description = "A modular framework for quickly creating kalman filters"
authors = [
    {name = "Walter Livingston",email = "wblivingston18@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy (>=2.2.6,<3.0.0)",
    "quaternions @ git+https://github.com/walterlivingston/quaternions@python",
    "scipy (>=1.15.3,<2.0.0)",
    "matplotlib (>=3.10.5,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pandas = "^2.3.0"

